### ISSUE TITLE
Numpy accuracy

### ISSUE THREAD

**Issue by henryiii** [nschloe/accupy#7]
I'm not seeing `numpy.sum` being that inaccurate, for example:

```python
>>> import numpy as np
>>> import math
>>> np.random.seed(42)
>>> dist = np.hstack([
...     np.random.normal(loc=1, scale=2., size=500_000),
...     np.random.normal(loc=1, scale=.5, size=500_000)
... ])

 # fsum vs. naive
>>> math.fsum(dist) - sum(dist)
5.820766091346741e-10

 # fsum vs. np.sum
>>> math.fsum(dist) - np.sum(dist)
0.0

# Check with 32 bit, fsum vs. naive
>>> math.fsum(dist.astype(np.float32)) - sum(dist.astype(np.float32), np.float32(0))
-20.27040922746528

# Check with 32 bit, fsum vs. np.sum
>>> math.fsum(dist.astype(np.float32)) - np.sum(dist.astype(np.float32))
-0.1454092274652794

# Check with 32 bit fsum vs. 64 bit fsum
>>> math.fsum(dist) - math.fsum(dist.astype(np.float32))
-2.3222528398036957e-06
```

**Comment by nschloe** [comment]
That's because your `dist` array is very well-conditioned:
```
cond = math.fsum(abs(dist)) / abs(math.fsum(q))
# 1.396953483206867
```
Try the same on the array `p` of
```
p, exact, cond = accupy.generate_ill_conditioned_sum(100, 1.0e20)
```
and you'll see `numpy.sum` fail. (That's the first example the main readme btw.)

**Comment by henryiii** [comment]
Ahh, you mention numpy does use pairwise summation. I'd at least put an example of something a bit better conditioned (summing distributions and similar sized values are quite common), or mention that numpy at least works much better than naive summing in many cases.

**Comment by nschloe** [comment]
If more people get tricked by this, I'll add something to the readme. Thanks for the good suggestion!
